# Generated by Django 5.2.9 on 2025-12-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'تصنيف', 'verbose_name_plural': 'التصنيفات'},
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#94a3b8', max_length=7, verbose_name='اللون'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='اسم التصنيف'),
        ),
    ]
