"""
Models for study sets, flashcards, and quizzes.
"""

from django.db import models
from django.contrib.auth.models import User


class StudySet(models.Model):
    """
    A study set containing either flashcards or quiz questions.
    Generated by AI from user-provided text or PDF.
    """
    TYPE_CHOICES = [
        ('flashcards', 'بطاقات تعليمية'),
        ('quiz', 'اختبار'),
    ]

    LANGUAGE_CHOICES = [
        ('ar', 'العربية'),
        ('en', 'English'),
    ]

    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='study_sets',
        verbose_name='المالك'
    )
    set_type = models.CharField(
        max_length=20,
        choices=TYPE_CHOICES,
        verbose_name='نوع المجموعة'
    )
    language = models.CharField(
        max_length=2,
        choices=LANGUAGE_CHOICES,
        verbose_name='اللغة'
    )
    title = models.CharField(
        max_length=200,
        blank=True,
        verbose_name='العنوان'
    )
    source_text = models.TextField(
        verbose_name='النص المصدر',
        help_text='النص الأصلي المستخدم لإنشاء المجموعة'
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'مجموعة دراسية'
        verbose_name_plural = 'المجموعات الدراسية'
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.get_set_type_display()} - {self.title or "بدون عنوان"}'

    @property
    def item_count(self):
        """Number of items (flashcards or questions) in this set."""
        if self.set_type == 'flashcards':
            return self.flashcards.count()
        return self.questions.count()

    @property
    def is_shared(self):
        """Check if this study set has been shared in any post."""
        return self.posts.filter(deleted_at__isnull=True).exists()


class Flashcard(models.Model):
    """A single flashcard with question and answer."""
    study_set = models.ForeignKey(
        StudySet,
        on_delete=models.CASCADE,
        related_name='flashcards'
    )
    index = models.PositiveIntegerField(verbose_name='الترتيب')
    question = models.TextField(verbose_name='السؤال')
    answer = models.TextField(verbose_name='الإجابة')

    class Meta:
        verbose_name = 'بطاقة تعليمية'
        verbose_name_plural = 'البطاقات التعليمية'
        ordering = ['index']
        unique_together = ('study_set', 'index')

    def __str__(self):
        return f'بطاقة {self.index + 1}: {self.question[:50]}'


class QuizQuestion(models.Model):
    """A single quiz question with multiple choice options."""
    study_set = models.ForeignKey(
        StudySet,
        on_delete=models.CASCADE,
        related_name='questions'
    )
    index = models.PositiveIntegerField(verbose_name='الترتيب')
    question = models.TextField(verbose_name='السؤال')
    options = models.JSONField(
        verbose_name='الخيارات',
        help_text='قائمة من 4 خيارات'
    )
    correct_index = models.PositiveSmallIntegerField(
        verbose_name='رقم الإجابة الصحيحة',
        help_text='0-3'
    )
    explanation = models.TextField(
        verbose_name='الشرح',
        help_text='شرح للإجابة الصحيحة والخاطئة'
    )

    class Meta:
        verbose_name = 'سؤال اختبار'
        verbose_name_plural = 'أسئلة الاختبار'
        ordering = ['index']
        unique_together = ('study_set', 'index')

    def __str__(self):
        return f'سؤال {self.index + 1}: {self.question[:50]}'

    @property
    def correct_answer(self):
        """Get the correct answer text."""
        if 0 <= self.correct_index < len(self.options):
            return self.options[self.correct_index]
        return None
