# Generated by Django 5.2.9 on 2025-12-31 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_type', models.CharField(choices=[('flashcards', 'بطاقات تعليمية'), ('quiz', 'اختبار')], max_length=20, verbose_name='نوع المجموعة')),
                ('language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], max_length=2, verbose_name='اللغة')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='العنوان')),
                ('source_text', models.TextField(help_text='النص الأصلي المستخدم لإنشاء المجموعة', verbose_name='النص المصدر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sets', to=settings.AUTH_USER_MODEL, verbose_name='المالك')),
            ],
            options={
                'verbose_name': 'مجموعة دراسية',
                'verbose_name_plural': 'المجموعات الدراسية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(verbose_name='الترتيب')),
                ('question', models.TextField(verbose_name='السؤال')),
                ('options', models.JSONField(help_text='قائمة من 4 خيارات', verbose_name='الخيارات')),
                ('correct_index', models.PositiveSmallIntegerField(help_text='0-3', verbose_name='رقم الإجابة الصحيحة')),
                ('explanation', models.TextField(help_text='شرح للإجابة الصحيحة والخاطئة', verbose_name='الشرح')),
                ('study_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='study.studyset')),
            ],
            options={
                'verbose_name': 'سؤال اختبار',
                'verbose_name_plural': 'أسئلة الاختبار',
                'ordering': ['index'],
                'unique_together': {('study_set', 'index')},
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(verbose_name='الترتيب')),
                ('question', models.TextField(verbose_name='السؤال')),
                ('answer', models.TextField(verbose_name='الإجابة')),
                ('study_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='study.studyset')),
            ],
            options={
                'verbose_name': 'بطاقة تعليمية',
                'verbose_name_plural': 'البطاقات التعليمية',
                'ordering': ['index'],
                'unique_together': {('study_set', 'index')},
            },
        ),
    ]
