# Generated by Django 5.2.9 on 2026-01-01 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='معرف المحتوى')),
                ('reason', models.CharField(choices=[('hate_speech', 'خطاب كراهية'), ('spam', 'محتوى مزعج (سبام)'), ('inappropriate', 'محتوى غير لائق'), ('misinformation', 'معلومات مضللة'), ('harassment', 'تحرش أو إساءة'), ('other', 'أخرى')], max_length=20, verbose_name='سبب البلاغ')),
                ('details', models.TextField(blank=True, verbose_name='تفاصيل إضافية')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'تمت الموافقة'), ('dismissed', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع المحتوى')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_submitted', to=settings.AUTH_USER_MODEL, verbose_name='المُبلِّغ')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='المُراجع')),
            ],
            options={
                'verbose_name': 'بلاغ',
                'verbose_name_plural': 'البلاغات',
                'ordering': ['-created_at'],
                'unique_together': {('reporter', 'content_type', 'object_id')},
            },
        ),
    ]
